#!/usr/bin/env python3
"""直前に実機取得したhooks/listから、repo専用のhook信頼設定を生成する。

snapshot自体から取得時刻の真正性は証明できない。適用前に必ず実機で再取得する。
"""

import argparse
from datetime import datetime, timezone
import difflib
import hashlib
import json
import os
from pathlib import Path
import re
import sys

from install_crew_hooks import ROOT, atomic_write, generated_hooks, snapshot, verify_snapshot


HEADER = "# Generated by scripts/codex_hook_state.py\n"
EVENTS = {"SessionStart": "sessionStart", "UserPromptSubmit": "userPromptSubmit",
          "Stop": "stop", "SubagentStop": "subagentStop"}


def digest(data):
    return "sha256:" + hashlib.sha256(data).hexdigest()


def snake(event):
    return re.sub(r"(?<!^)(?=[A-Z])", "_", event).lower()


def disabled_commands(home):
    commands = {f"'{home}/.codex/hooks/{name}.sh'" for name in
                ("cmux-notify", "aggregate-learnings", "capture-learning")}
    commands.update({f'bash "$HOME/Workspace/Obsidian/.codex/hooks/{name}.sh"' for name in
                     ("capture-session", "inbox-check")})
    commands.add("cd ~/Workspace/mcp/serena && uv run serena-mcp-server")
    return commands


def selected_states(document, root, home):
    project_path = str(root / ".codex/hooks.json")
    user_path = str(home / ".codex/hooks.json")
    generated = generated_hooks(root, "codex")
    if set(generated) != set(EVENTS):
        raise ValueError("manifestの4イベントが一致しません。レビューが必要です")
    expected = {
        f"{project_path}:{snake(event)}:0:0": (EVENTS[event], generated[event][0]["hooks"][0]["command"])
        for event in EVENTS
    }
    data = document["result"]["data"]
    matching = [entry for entry in data if entry.get("cwd") == str(root)]
    if len(matching) != 1 or matching[0].get("errors"):
        raise ValueError("snapshotのcwdまたはerrorsが不正です。実機で再取得してください")
    states, seen, warnings = [], set(), []
    for hook in matching[0]["hooks"]:
        source, path, key = hook.get("source"), hook.get("sourcePath"), hook.get("key")
        if hook.get("isManaged"):
            continue
        project_claim = source == "project" or path == project_path or (isinstance(key, str) and key.startswith(project_path + ":"))
        if project_claim:
            pair = expected.get(key)
            if (source != "project" or path != project_path or pair is None
                    or hook.get("handlerType") != "command" or pair != (hook.get("eventName"), hook.get("command"))
                    or key in seen or not re.fullmatch(r"sha256:[0-9a-f]{64}", hook.get("currentHash", ""))):
                raise ValueError("repo hookが生成内容と一対一で一致しません。レビューが必要です")
            seen.add(key)
            states.append({"source": source, "sourcePath": path, "key": key,
                           "command": hook["command"], "enabled": True, "trusted_hash": hook["currentHash"]})
        elif source == "user" and path == user_path:
            event = hook.get("eventName", "")
            valid_key = isinstance(key, str) and re.fullmatch(re.escape(user_path + ":" + snake(event) + ":") + r"[0-9]+:[0-9]+", key)
            if hook.get("command") in disabled_commands(home) and hook.get("handlerType") == "command" and valid_key:
                states.append({"source": source, "sourcePath": path, "key": key,
                               "command": hook["command"], "enabled": False})
            else:
                # 外部hookの安全性を推測せず、設定は変更せずに件数を報告する。
                warnings.append("未変更のuser hookがあります。必要に応じて個別レビューしてください")
    if seen != set(expected) or len({item["key"] for item in states}) != len(states):
        raise ValueError("4イベントが不足・重複しています。レビューが必要です")
    return sorted(states, key=lambda item: item["key"]), warnings


def render_config(states):
    lines = [HEADER.rstrip(), "notify = []", "", "[features]", "hooks = true"]
    for state in states:
        lines.extend(["", f'[hooks.state.{json.dumps(state["key"], ensure_ascii=False)}]',
                      "enabled = " + str(state["enabled"]).lower()])
        if state["enabled"]:
            lines.append("trusted_hash = " + json.dumps(state["trusted_hash"]))
    return "\n".join(lines) + "\n"


def verify_previous(config_bytes, sidecar_bytes, root):
    if config_bytes is None and sidecar_bytes is None:
        return
    if config_bytes is None or sidecar_bytes is None:
        raise ValueError("既存configまたは管理記録が欠落しています。自動上書きせずレビューしてください")
    previous = json.loads(sidecar_bytes)
    if (previous.get("schema_version") != 1 or previous.get("root") != str(root)
            or previous.get("generated_config_hash") != digest(config_bytes)
            or render_config(previous["states"]).encode() != config_bytes):
        raise ValueError("既存configまたは管理記録に独自変更があります。自動上書きせずレビューしてください")


def launch_overrides(root, environ=None):
    """projectでは適用されない信頼状態を明示した起動設定へ変換する。"""
    env = os.environ if environ is None else environ
    default_home = (Path.home() / ".codex").resolve()
    if Path(env.get("CODEX_HOME", str(default_home))).expanduser().resolve() != default_home:
        raise ValueError("この設定は既定CODEX_HOME専用です。別のCODEX_HOMEではhook状態を再設計してください")
    config = snapshot(root / ".codex/config.toml")
    sidecar = snapshot(root / "docs/codex-direct/local-hook-state.json")
    verify_previous(config, sidecar, root)
    if sidecar is None:
        raise ValueError("hook state未設定。実機snapshotから設定してください")
    states = json.loads(sidecar)["states"]
    user_hooks = json.loads((Path.home() / ".codex/hooks.json").read_text())["hooks"]
    event_keys = {snake(event): event for event in user_hooks}
    # 保存後にglobal hookの順序が変わっていたら別handlerを止めない。
    for item in states:
        if item["source"] != "user":
            continue
        _, event, group, handler = item["key"].rsplit(":", 3)
        try:
            actual = user_hooks[event_keys[event]][int(group)]["hooks"][int(handler)]["command"]
        except (KeyError, IndexError, ValueError):
            raise ValueError("user hook構成変更。snapshotを再取得してください")
        if actual != item["command"]:
            raise ValueError("user hook構成変更。snapshotを再取得してください")
    args = ["-c", "notify=[]", "-c", "features.hooks=true"]
    # -c のdotted key分割にファイル名の '.' を渡さない。state全体をTOML値にする。
    entries = []
    for item in states:
        fields = "enabled=" + str(item["enabled"]).lower()
        if item["enabled"]:
            fields += ",trusted_hash=" + json.dumps(item["trusted_hash"])
        entries.append(json.dumps(item["key"]) + "={" + fields + "}")
    args.extend(["-c", "hooks.state={" + ",".join(entries) + "}"])
    return args


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--snapshot", type=Path, required=True)
    parser.add_argument("--root", type=Path, default=ROOT)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--apply", action="store_true")
    args = parser.parse_args(argv)
    root = args.root.resolve()
    backup = None
    try:
        raw = args.snapshot.read_bytes()
        states, warnings = selected_states(json.loads(raw), root, Path.home())
        for warning in sorted(set(warnings)):
            print(f"警告: {warning}（{len(warnings)}件）", file=sys.stderr)
        config = root / ".codex/config.toml"
        sidecar = root / "docs/codex-direct/local-hook-state.json"
        config_before, sidecar_before = snapshot(config), snapshot(sidecar)
        verify_previous(config_before, sidecar_before, root)
        content = render_config(states)
        record = json.dumps({"schema_version": 1, "root": str(root), "snapshot_hash": digest(raw),
                             "generated_config_hash": digest(content.encode()), "states": states},
                            ensure_ascii=False, indent=2) + "\n"
        pending = [(path, text, before) for path, text, before in
                   ((config, content, config_before), (sidecar, record, sidecar_before))
                   if text.encode() != before]
        for path, content, before in pending:
            sys.stdout.writelines(difflib.unified_diff((before or b"").decode().splitlines(True), content.splitlines(True),
                                                     fromfile=str(path.relative_to(root)), tofile=str(path.relative_to(root)) + " (generated)"))
        if args.apply and pending:
            for path, before in ((config, config_before), (sidecar, sidecar_before)):
                verify_snapshot(path, before)
            backup = root / "docs/codex-direct/backups" / ("shared-state-" + datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S%fZ"))
            backup.mkdir(parents=True, exist_ok=False)
            for path, _, before in pending:
                if before is not None:
                    target = backup / path.relative_to(root)
                    target.parent.mkdir(parents=True, exist_ok=True)
                    target.write_bytes(before)
            for path, content, before in pending:
                atomic_write(path, content, before)
            print(f"退避先: {backup}", file=sys.stderr)
        return 1 if args.check and pending else 0
    except (OSError, ValueError, KeyError, TypeError) as error:
        print(f"hook state生成を拒否: {error}", file=sys.stderr)
        if backup:
            print(f"退避先: {backup}。途中の変更は自動rollbackしません。現在の設定と管理記録をレビューしてください。", file=sys.stderr)
        print("実機snapshotを再取得し、競合を解消後に --check で確認してから --apply を再実行してください。", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
