#!/usr/bin/env python3
"""直前に実機取得したhooks/listから、repo専用のhook信頼設定を生成する。

snapshot自体から取得時刻の真正性は証明できない。適用前に必ず実機で再取得する。
"""

import argparse
from contextlib import nullcontext
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import re
import sys

from install_crew_hooks import ROOT, generated_hooks, snapshot
from codex_config_composer import (Document, compose_hooks, hook_owned, hook_unowned, lock, restore_hooks,
                                   atomic_write as compose_write, atomic_remove, verify_hook_section, sha)


HEADER = "# Generated by scripts/codex_hook_state.py\n"
EVENTS = {"SessionStart": "sessionStart", "Stop": "stop", "SubagentStop": "subagentStop"}


def digest(data):
    return "sha256:" + hashlib.sha256(data).hexdigest()


def snake(event):
    return re.sub(r"(?<!^)(?=[A-Z])", "_", event).lower()


def disabled_commands(home):
    commands = {f"'{home}/.codex/hooks/{name}.sh'" for name in
                ("cmux-notify", "aggregate-learnings", "capture-learning")}
    commands.update({f'bash "$HOME/Workspace/Obsidian/.codex/hooks/{name}.sh"' for name in
                     ("capture-session", "inbox-check")})
    commands.add("cd ~/Workspace/mcp/serena && uv run serena-mcp-server")
    return commands


def selected_states(document, root, home):
    project_path = str(root / ".codex/hooks.json")
    user_path = str(home / ".codex/hooks.json")
    generated = generated_hooks(root, "codex")
    if not generated or set(generated) - set(EVENTS):
        raise ValueError("manifestのCodex登録イベントが未対応です。レビューが必要です")
    expected = {
        f"{project_path}:{snake(event)}:0:0": (EVENTS[event], generated[event][0]["hooks"][0]["command"])
        for event in generated
    }
    data = document["result"]["data"]
    matching = [entry for entry in data if entry.get("cwd") == str(root)]
    if len(matching) != 1 or matching[0].get("errors"):
        raise ValueError("snapshotのcwdまたはerrorsが不正です。実機で再取得してください")
    states, seen, warnings = [], set(), []
    for hook in matching[0]["hooks"]:
        source, path, key = hook.get("source"), hook.get("sourcePath"), hook.get("key")
        if hook.get("isManaged"):
            continue
        project_claim = source == "project" or path == project_path or (isinstance(key, str) and key.startswith(project_path + ":"))
        if project_claim:
            pair = expected.get(key)
            if (source != "project" or path != project_path or pair is None
                    or hook.get("handlerType") != "command" or pair != (hook.get("eventName"), hook.get("command"))
                    or key in seen or not re.fullmatch(r"sha256:[0-9a-f]{64}", hook.get("currentHash", ""))):
                raise ValueError("repo hookが生成内容と一対一で一致しません。レビューが必要です")
            seen.add(key)
            states.append({"source": source, "sourcePath": path, "key": key,
                           "command": hook["command"], "enabled": True, "trusted_hash": hook["currentHash"]})
        elif source == "user" and path == user_path:
            event = hook.get("eventName", "")
            valid_key = isinstance(key, str) and re.fullmatch(re.escape(user_path + ":" + snake(event) + ":") + r"[0-9]+:[0-9]+", key)
            if hook.get("command") in disabled_commands(home) and hook.get("handlerType") == "command" and valid_key:
                states.append({"source": source, "sourcePath": path, "key": key,
                               "command": hook["command"], "enabled": False})
            else:
                # 外部hookの安全性を推測せず、設定は変更せずに件数を報告する。
                warnings.append("未変更のuser hookがあります。必要に応じて個別レビューしてください")
    if seen != set(expected) or len({item["key"] for item in states}) != len(states):
        raise ValueError("manifest登録イベントが不足・重複しています。レビューが必要です")
    return sorted(states, key=lambda item: item["key"]), warnings


def render_config(states):
    lines = [HEADER.rstrip(), "notify = []", "", "[features]", "hooks = true"]
    for state in states:
        lines.extend(["", f'[hooks.state.{json.dumps(state["key"], ensure_ascii=False)}]',
                      "enabled = " + str(state["enabled"]).lower()])
        if state["enabled"]:
            lines.append("trusted_hash = " + json.dumps(state["trusted_hash"]))
    return "\n".join(lines) + "\n"


def verify_previous(config_bytes, sidecar_bytes, root):
    if config_bytes is None and sidecar_bytes is None:
        return
    if config_bytes is not None and sidecar_bytes is None:
        data = Document(config_bytes.decode()).data
        if data.get("notify") is not None or data.get("features", {}).get("hooks") is not None:
            raise ValueError("台帳なしのhook所有区画があります")
        return
    if config_bytes is None or sidecar_bytes is None:
        raise ValueError("既存configまたは管理記録が欠落しています。自動上書きせずレビューしてください")
    previous = json.loads(sidecar_bytes)
    if previous.get("root") != str(root):
        raise ValueError("hook台帳のrootが一致しません")
    if previous.get("schema_version") == 1:
        if (previous.get("generated_config_hash") != digest(config_bytes)
                or render_config(previous["states"]).encode() != config_bytes):
            raise ValueError("旧hook schema1の全体hash/生成内容が一致しません")
    elif previous.get("schema_version") == 2 and previous.get("status") == "applied":
        verify_hook_section(config_bytes.decode(), previous["owned_after"])
    else:
        raise ValueError("hook台帳が途中または未知schemaです。復旧が必要です")


def reject_managed_symlinks(config, sidecar):
    for path in (config, sidecar):
        if path.is_symlink():
            raise ValueError("symlink管理ファイルは台帳/backup作成前に拒否します")


def recover_or_rollback(root, state_dir, rollback=False):
    config = root / ".codex/config.toml"
    sidecar = root / "docs/codex-direct/local-hook-state.json"
    reject_managed_symlinks(config, sidecar)
    with lock(state_dir):
        reject_managed_symlinks(config, sidecar)
        sidecar_bytes = sidecar.read_bytes()
        record = json.loads(sidecar_bytes)
        if record.get("schema_version") != 2 or record.get("root") != str(root):
            raise ValueError("schema2の復旧対象ではありません")
        config_bytes = snapshot(config)
        current = (config_bytes or b"").decode()
        backup = Path(record["backup"])
        old_sidecar = snapshot(backup / "sidecar.json")
        def restored_sidecar(restored_text):
            if old_sidecar is None:
                return None
            prior = json.loads(old_sidecar)
            if prior.get("schema_version") == 1:
                # 全体hashの旧台帳は無関係区画の変化と両立しない。新台帳で
                # 区画だけ記録し、実機snapshot更新までlauncherを停止する。
                keys = [item["key"] for item in prior["states"]]
                safe = {"schema_version": 2, "status": "applied", "root": str(root),
                        "states": prior["states"], "owned_after": hook_owned(Document(restored_text).data, keys),
                        "generation": record["generation"] + 1, "requires_fresh_snapshot": True}
                return (json.dumps(safe, ensure_ascii=False, indent=2) + "\n").encode()
            return old_sidecar
        if record["status"] == "rollback_pending" and not rollback:
            keys = sorted(record["owned_after"]["entries"])
            owned = hook_owned(Document(current).data, keys)
            if owned == record["owned_before"]:
                previous = restored_sidecar(current)
                if previous is None:
                    atomic_remove(sidecar, sidecar_bytes)
                else:
                    compose_write(sidecar, previous, sidecar_bytes)
                return "rolled_back"
            if owned == record["owned_after"]:
                record["status"] = "applied"
                compose_write(sidecar, (json.dumps(record, ensure_ascii=False, indent=2) + "\n").encode(), sidecar_bytes)
                return "rollback_not_applied"
            raise ValueError("rollback途中のhook区画がbefore/afterと不一致です")
        if rollback:
            if record["status"] != "applied":
                raise ValueError("pending中は先に--recoverしてください")
            restored = restore_hooks(current, record["owned_after"], record["before_fragments"])
            record["status"] = "rollback_pending"
            compose_write(sidecar, (json.dumps(record, ensure_ascii=False, indent=2) + "\n").encode(), sidecar_bytes)
            sidecar_bytes = sidecar.read_bytes()
            if not record.get("before_existed", True) and not hook_unowned(Document(restored).data, record["owned_after"]["entries"]) and not restored.strip():
                atomic_remove(config, config_bytes)
            else:
                compose_write(config, restored.encode(), config_bytes)
            previous = restored_sidecar(restored)
            if previous is None:
                atomic_remove(sidecar, sidecar_bytes)
            else:
                compose_write(sidecar, previous, sidecar_bytes)
            return "rolled_back"
        if record["status"] != "pending":
            raise ValueError("pending世代がありません")
        keys = sorted(record["owned_after"]["entries"])
        owned = hook_owned(Document(current).data, keys)
        if owned == record["owned_after"]:
            record["status"] = "applied"
            compose_write(sidecar, (json.dumps(record, ensure_ascii=False, indent=2) + "\n").encode(), sidecar_bytes)
            return "applied"
        if owned == record["owned_before"]:
            if old_sidecar is None:
                atomic_remove(sidecar, sidecar_bytes)
            else:
                compose_write(sidecar, old_sidecar, sidecar_bytes)
            return "not_applied"
        raise ValueError("hook区画がbefore/afterのいずれとも不一致。手動確認が必要です")


def launch_overrides(root, environ=None):
    """projectでは適用されない信頼状態を明示した起動設定へ変換する。"""
    env = os.environ if environ is None else environ
    default_home = (Path.home() / ".codex").resolve()
    if Path(env.get("CODEX_HOME", str(default_home))).expanduser().resolve() != default_home:
        raise ValueError("この設定は既定CODEX_HOME専用です。別のCODEX_HOMEではhook状態を再設計してください")
    config_path = root / ".codex/config.toml"
    sidecar_path = root / "docs/codex-direct/local-hook-state.json"
    reject_managed_symlinks(config_path, sidecar_path)
    config = snapshot(config_path)
    sidecar = snapshot(sidecar_path)
    verify_previous(config, sidecar, root)
    if sidecar is None:
        raise ValueError("hook state未設定。実機snapshotから設定してください")
    states = json.loads(sidecar)["states"]
    if json.loads(sidecar).get("requires_fresh_snapshot"):
        raise ValueError("rollback後のhookは新しい実機snapshotで再照合してください")
    user_states = [item for item in states if item["source"] == "user"]
    if user_states:
        user_hooks = json.loads((Path.home() / ".codex/hooks.json").read_text())["hooks"]
        event_keys = {snake(event): event for event in user_hooks}
    # 保存後にglobal hookの順序が変わっていたら別handlerを止めない。
    for item in user_states:
        _, event, group, handler = item["key"].rsplit(":", 3)
        try:
            actual = user_hooks[event_keys[event]][int(group)]["hooks"][int(handler)]["command"]
        except (KeyError, IndexError, ValueError):
            raise ValueError("user hook構成変更。snapshotを再取得してください")
        if actual != item["command"]:
            raise ValueError("user hook構成変更。snapshotを再取得してください")
    args = ["-c", "notify=[]", "-c", "features.hooks=true"]
    # -c のdotted key分割にファイル名の '.' を渡さない。state全体をTOML値にする。
    entries = []
    for item in states:
        fields = "enabled=" + str(item["enabled"]).lower()
        if item["enabled"]:
            fields += ",trusted_hash=" + json.dumps(item["trusted_hash"])
        entries.append(json.dumps(item["key"]) + "={" + fields + "}")
    args.extend(["-c", "hooks.state={" + ",".join(entries) + "}"])
    return args


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--snapshot", type=Path)
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--state-dir", type=Path, default=Path.home() / ".codex/config-composer")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--apply", action="store_true")
    mode.add_argument("--recover", action="store_true")
    mode.add_argument("--rollback", action="store_true")
    args = parser.parse_args(argv)
    root = args.root.resolve()
    try:
        if root == ROOT.resolve() and (args.apply or args.recover or args.rollback):
            if args.state_dir.resolve() != (Path.home() / ".codex/config-composer").resolve():
                raise ValueError("実repoのprivate台帳は~/.codex/config-composer固定です")
        config = root / ".codex/config.toml"
        sidecar = root / "docs/codex-direct/local-hook-state.json"
        reject_managed_symlinks(config, sidecar)
        if args.recover or args.rollback:
            print(recover_or_rollback(root, args.state_dir, args.rollback))
            return 0
        if args.snapshot is None:
            raise ValueError("--snapshotが必要です")
        raw = args.snapshot.read_bytes()
        states, warnings = selected_states(json.loads(raw), root, Path.home())
        for warning in sorted(set(warnings)):
            print(f"警告: {warning}（{len(warnings)}件）", file=sys.stderr)
        with lock(args.state_dir) if args.apply else nullcontext():
            reject_managed_symlinks(config, sidecar)
            config_before, sidecar_before = snapshot(config), snapshot(sidecar)
            verify_previous(config_before, sidecar_before, root)
            previous = json.loads(sidecar_before) if sidecar_before else None
            previous_keys = [item["key"] for item in previous["states"]] if previous else []
            expected = previous["owned_after"] if previous and previous["schema_version"] == 2 else None
            if previous and previous["schema_version"] == 1:
                # 旧schema1は全体一致を確認済み。新composerに渡す前に旧所有区画だけ除去する。
                old = Document(config_before.decode())
                old.remove_key((), "notify")
                old.remove_key(("features",), "hooks")
                for key in previous_keys:
                    old.remove_tree(("hooks", "state", key))
                base = old.render()
            else:
                base = (config_before or b"").decode()
            content, before_owned, after_owned, fragments = compose_hooks(base, states, expected, previous_keys)
            if previous and previous["schema_version"] == 1:
                before_doc = Document(config_before.decode())
                all_keys = sorted(set(previous_keys) | {item["key"] for item in states})
                before_owned = hook_owned(before_doc.data, all_keys)
                fragments = {"notify": before_doc.remove_key((), "notify"),
                             "features.hooks": before_doc.remove_key(("features",), "hooks"),
                             "entries": {key: before_doc.remove_tree(("hooks", "state", key))
                                         for key in all_keys}}
            if previous and previous["schema_version"] == 2 and previous["states"] == states:
                content = config_before.decode()
            changed = content.encode() != config_before
            record = {"schema_version": 2, "status": "applied", "root": str(root),
                      "snapshot_hash": digest(raw), "states": states, "owned_after": after_owned,
                      "owned_before": before_owned, "before_fragments": fragments,
                      "before_existed": config_before is not None,
                      "generation": previous.get("generation", 0) + 1 if previous else 1}
            record_bytes = (json.dumps(record, ensure_ascii=False, indent=2) + "\n").encode()
            if (not changed and previous and previous["schema_version"] == 2 and previous["states"] == states
                    and previous.get("snapshot_hash") == digest(raw)):
                record_bytes = sidecar_before
            pending = changed or record_bytes != sidecar_before
            if pending:
                print(json.dumps({"config": str(config.relative_to(root)), "changed": changed,
                                  "before_hash": sha(config_before or b""), "after_hash": sha(content.encode()),
                                  "states": len(states), "schema": 2}, ensure_ascii=False))
            if args.apply and pending:
                backup = args.state_dir / "backups" / ("hook-" + datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S%fZ"))
                backup.mkdir(parents=True, mode=0o700, exist_ok=False)
                for name, data in (("config.toml", config_before), ("sidecar.json", sidecar_before)):
                    if data is not None:
                        path = backup / name
                        path.write_bytes(data)
                        path.chmod(0o600)
                record["status"] = "pending"
                record["backup"] = str(backup)
                pending_bytes = (json.dumps(record, ensure_ascii=False, indent=2) + "\n").encode()
                compose_write(sidecar, pending_bytes, sidecar_before)
                if changed:
                    compose_write(config, content.encode(), config_before)
                record["status"] = "applied"
                compose_write(sidecar, (json.dumps(record, ensure_ascii=False, indent=2) + "\n").encode(), pending_bytes)
        return 1 if args.check and pending else 0
    except (OSError, ValueError, KeyError, TypeError) as error:
        print(f"hook state生成を拒否: {error}", file=sys.stderr)
        print("途中失敗時はprivate backupと台帳を照合し、区画が適用後と一致する場合に限りrollbackしてください。", file=sys.stderr)
        print("実機snapshotを再取得し、競合を解消後に --check で確認してから --apply を再実行してください。", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
